config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see
  # https://guides.rubyonrails.org/routing.html
  root 'home#index'

  get 'sign-in', to: 'sessions#new', as: :new_session
  resource :session, only: %i[show create destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/google_id_token.rb
class GoogleIdToken
  include ActiveModel::Validations

  attr_reader :token, :header, :payload

  validates :token, presence: true

  validate :audience_matches_project_id,
           :issuer_matches_the_expected_issuer,
           :expires_in_the_future,
           :issued_in_the_past,
           :authenticated_in_the_past

  def initialize(token)
    @token = token
    @payload, @header = JWT.decode(@token, nil, false)
                           .map(&:with_indifferent_access)
  end

  def issuer
    payload[:iss]
  end

  def audience
    payload[:aud]
  end

  def user_id
    payload[:user_id]
  end

  def subject
    payload[:sub]
  end

  # Only available with email+password provider:
  def email
    payload[:email]
  end

  # Only available with email+password provider:
  def email_verified
    payload[:email_verified]
  end

  def authenticated_at
    @authenticated_at ||= Time.at(payload[:auth_time])
  end

  def issued_at
    @issued_at ||= Time.at(payload[:iat])
  end

  def expires_at
    @expires_at ||= Time.at(payload[:exp])
  end

  def self.project_id
    ENV.fetch 'GOOGLE_CLOUD_PROJECT'
  end

  delegate :project_id, to: :class, prefix: :configured

  def user
    User.new id: user_id, email: email, email_verified: email_verified
  end

  protected

  def expires_in_the_future
    return if Time.now < expires_at

    errors.add :token, 'has expired'
  end

  def issued_in_the_past
    return if Time.now > issued_at

    errors.add :token, 'issued at invalid date'
  end

  def authenticated_in_the_past
    return if Time.now > authenticated_at

    errors.add :token, 'authenticated at invalid date'
  end

  def audience_matches_project_id
    return if audience == configured_project_id

    errors.add :token, "unexpected audience '#{audience}'"
  end

  def issuer_matches_the_expected_issuer
    return if issuer == "https://securetoken.google.com/#{configured_project_id}"

    errors.add :token, "unexpected issuer '#{issuer}'"
  end
end

app/models/user.rb
class User
  extend ActiveModel::Naming
  include ActiveModel::Serialization
  extend ActiveModel::Translation

  attr_reader :id, :email, :email_verified

  def initialize(attributes = {})
    attributes = attributes.with_indifferent_access
    @id = attributes[:id]
    @email = attributes[:email]
    @email_verified = attributes[:email_verified]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # GET /session
  def show
  end

  # GET /sign-in
  def new
    redirect_to root_path, notice: 'Already signed in' if user_signed_in?
  end

  # POST /session
  def create
    @token = GoogleIdToken.new(session_params[:token])
    sign_in_user(@token.user) if @token.valid?

    respond_to do |format|
      if user_signed_in?
        format.html { redirect_to root_path, notice: 'Session was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # DELETE /session
  def destroy
    sign_out_user
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Session was successfully destroyed.' }
    end
  end

  private

    # Only allow a list of trusted parameters through.
    def session_params
      params.require(:session).permit(:token)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def authenticate_user!
    return if user_signed_in?

    redirect_to new_session_path
  end

  def sign_in_user(user)
    session[:current_user] = user
  end

  def current_user
    User.new session[:current_user]
  end

  def user_signed_in?
    session.key? :current_user
  end

  def sign_out_user
    session.delete :current_user
  end
end

app/views/home/_authenticated.html.erb
<p>Hello <%= current_user.email %>!</p>

app/views/home/_unauthenticated.html.erb
<p>Let's begin with starting a session</p>
<%= link_to 'Sign in', new_session_path %>

app/views/home/index.html.erb
<div data-controller="hello">
  <h2>Home</h1>
  <p data-target="hello.output"></p>


  <% if user_signed_in? %>
    <%= render 'authenticated' %>
  <% else %>
    <%= render 'unauthenticated' %>
  <% end %>

  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsGoogleCloudDemo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Rails & Google Cloud Demo", root_path, class: "navbar-brand" %>

    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <li class="nav-item">
        <% if user_signed_in? %><%= link_to "Sign Out #{current_user.email}", session_path, method: :delete, class: 'nav-link' %>
        <% else %><%= link_to "Sign In", new_session_path, class: 'nav-link' %>
        <% end %>
      </li>
    </ul>
  </div>
</nav>